In [4]:
import torch
print(torch.__version__)


2.12.0+cpu


In [9]:
Matrix = torch.tensor([[1,1],[1,1]])
print(Matrix)
print(Matrix.ndim)
print(Matrix.shape)

tensor([[1, 1],
        [1, 1]])
2
torch.Size([2, 2])


In [10]:
TENSOR = torch.tensor([[[1,2,3],[3,4,5]],[[10,12,13],[14,56,0]]])
print(TENSOR)

tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[10, 12, 13],
         [14, 56,  0]]])


In [11]:
TENSOR.shape

torch.Size([2, 2, 3])

In [17]:
random_tensor = torch.rand(size=(3,4),dtype =torch.float32)
random_tensor

tensor([[0.4899, 0.5971, 0.7323, 0.3772],
        [0.8778, 0.8074, 0.8482, 0.3350],
        [0.2658, 0.2876, 0.3607, 0.8920]])

In [ ]:
#Used to generate ttensor with in range with step modification
#torch.arange(start,end,step)
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#zeros tensor
zeros_tensor = torch.zeros(size=(3,4))
print(zeros_tensor)
#Addition
x = torch.add(zeros_tensor ,10)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])


In [23]:
complex_tensor = torch.tensor([2+6j,4+5j], dtype=torch.complex64)
complex_tensor 

tensor([2.+6.j, 4.+5.j])

In [28]:
#Matrix multiplication
matrix1 = torch.tensor([1,2,3])
matrix2 = torch.tensor([2,3,4])
print("Elementwise multiplication")
print(matrix1 * matrix2)
print("Matrix multiplication")
print(torch.matmul(matrix1,matrix2))

Elementwise multiplication
tensor([ 2,  6, 12])
Matrix multiplication
tensor(20)


In [32]:
#calculate min ,max,mean ,sum
tensor_arith = torch.arange(0,200,10)
print(tensor_arith)
print(f"sum:{ tensor_arith.sum()}")
print(f"min:{ tensor_arith.min()}")
print(f"max:{ tensor_arith.max()}")
print(f"mean:{ tensor_arith.type(torch.float32).mean()}")

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190])
sum:1900
min:0
max:190
mean:95.0


In [40]:
# Create a tensor
import torch
x = torch.arange(1., 8)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [43]:
x_reshaped = x.reshape(1,7)
print(f"reshape x:{x_reshaped}")
z = x.view(1,7)
z,z.shape

reshape x:tensor([[1., 2., 3., 4., 5., 6., 7.]])


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [44]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [45]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [46]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [47]:
#Indexing (selecting data from tensors)

# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [54]:
y = torch.arange(1,19).reshape(2,3,3)
y,y.shape

# Let's index bracket by bracket
#print(f"First square bracket:\n{y[0]}") 
#print(f"Second square bracket: {y[0][0]}") 
#print(f"Third square bracket: {y[0][0][0]}")

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [58]:
y[1,1,0]

tensor(13)

In [60]:
#Reproducibility (trying to take the random out of random)
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])